# Generated by Django 4.2.3 on 2023-08-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_listing_bid_auction_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="buyer",
        ),
    ]
