# Generated by Django 4.2.3 on 2023-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="subtitle",
            field=models.CharField(max_length=64),
        ),
    ]
