# Generated by Django 4.2.3 on 2023-08-22 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watched_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
